name: webant_test_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  flutter_bloc: ^7.0.1
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.6
  cached_network_image: ^3.0.0
  connectivity: ^3.0.6
  intl: ^0.17.0
  get_it: ^7.1.3
  path: ^1.8.0
  json_annotation: ^4.0.1
  image_picker: ^0.8.1+3
  hive: ^2.0.4
  hive_flutter: 1.1.0
  path_provider: any
  mask_text_input_formatter: ^2.0.0
  phone_number: ^0.11.0+1
  equatable: ^2.0.3
  email_validator: ^2.0.1




dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^4.1.3
  hive_generator: ^1.1.0

  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
